version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: car_game_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cargamedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: car_game_flask
    volumes:
      - .:/app
    ports:
      - "5050:5000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/cargamedb
      - DB_HOST=db
      - DB_NAME=cargamedb
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  pgdata: